### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by laynd** [AnonGuy/groupme-discord#15]
I must say right away I have 0 knowledge when it comes to Python. I followed all directions. Went with ngrok option to expose webserver. I constantly get this error. What could be causing it? Running it on windows10 machine. 

```
C:\discord2groupme>py main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    discord_bot.main()
  File "C:\discord2groupme\discord_bot.py", line 99, in main
    Process(target=bot.run, args=(BOT_TOKEN,)).start()
  File "C:\Python\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Python\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python\lib\multiprocessing\context.py", line 320, in _Popen
    return Popen(process_obj)
  File "C:\Python\lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'WeakSet.__init__.<locals>._remove'

C:\discord2groupme>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect




```

**Comment by laynd** [comment]
Got some progress. So apparently installing requirements.txt is where I got stuck. This step does not complete without errors that is why I cannot start the service. Any ideas what is causing it? 

```
C:\Users\bizma\Documents\GitHub\groupme-discord>py -m pip install -r requirements.txt
Requirement already satisfied: Flask>=1.0.2 in c:\python\lib\site-packages (from -r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: aiohttp>=3.3.2 in c:\python\lib\site-packages (from -r requirements.txt (line 2)) (3.5.4)
Requirement already satisfied: requests>=2.18.4 in c:\python\lib\site-packages (from -r requirements.txt (line 3)) (2.21.0)
Requirement already satisfied: discord.py[voice] from git+https://github.com/Rapptz/discord.py/archive/rewrite.zip#egg=discord.py[voice] in c:\python\lib\site-packages (from -r requirements.txt (line 4)) (1.0.0)
Requirement already satisfied: Jinja2>=2.10 in c:\python\lib\site-packages (from Flask>=1.0.2->-r requirements.txt (line 1)) (2.10.1)
Requirement already satisfied: Werkzeug>=0.14 in c:\python\lib\site-packages (from Flask>=1.0.2->-r requirements.txt (line 1)) (0.15.2)
Requirement already satisfied: itsdangerous>=0.24 in c:\python\lib\site-packages (from Flask>=1.0.2->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: click>=5.1 in c:\python\lib\site-packages (from Flask>=1.0.2->-r requirements.txt (line 1)) (7.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\python\lib\site-packages (from aiohttp>=3.3.2->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\python\lib\site-packages (from aiohttp>=3.3.2->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: multidict<5.0,>=4.0 in c:\python\lib\site-packages (from aiohttp>=3.3.2->-r requirements.txt (line 2)) (4.5.2)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\python\lib\site-packages (from aiohttp>=3.3.2->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in c:\python\lib\site-packages (from aiohttp>=3.3.2->-r requirements.txt (line 2)) (19.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\lib\site-packages (from requests>=2.18.4->-r requirements.txt (line 3)) (2019.3.9)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\python\lib\site-packages (from requests>=2.18.4->-r requirements.txt (line 3)) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python\lib\site-packages (from requests>=2.18.4->-r requirements.txt (line 3)) (2.8)
Requirement already satisfied: websockets<7.0,>=6.0 in c:\python\lib\site-packages (from discord.py[voice]->-r requirements.txt (line 4)) (6.0)
Collecting PyNaCl==1.3.0 (from discord.py[voice]->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz
  Installing build dependencies ... error
  ERROR: Complete output from command 'C:\Python\python.exe' 'C:\Python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\bizma\AppData\Local\Temp\pip-build-env-ixx_vfsk\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cffi>=1.4.1; python_implementation != '"'"'PyPy'"'"'':
  ERROR: Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/2c/03/64c2d74bc381f9b8529151e7dda63921d3209be7b447bf876d96c115e7d3/wheel-0.33.2-py2.py3-none-any.whl
  Collecting cffi>=1.4.1
    Using cached https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz
      ERROR: Complete output from command python setup.py egg_info:
      ERROR: Traceback (most recent call last):
        File "C:\Python\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
          return self.find_available_vc_vers()[-1]
      IndexError: list index out of range

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\bizma\AppData\Local\Temp\pip-install-3gk75wka\cffi\setup.py", line 127, in <module>
          if sys.platform == 'win32' and uses_msvc():
        File "C:\Users\bizma\AppData\Local\Temp\pip-install-3gk75wka\cffi\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
        File "C:\Python\lib\distutils\command\config.py", line 225, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Python\lib\distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Python\lib\distutils\_msvccompiler.py", line 346, in compile
          self.initialize()
        File "C:\Python\lib\distutils\_msvccompiler.py", line 239, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Python\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
          return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
        File "C:\Python\lib\site-packages\setuptools\msvc.py", line 843, in __init__
          self.si = SystemInfo(self.ri, vc_ver)
        File "C:\Python\lib\site-packages\setuptools\msvc.py", line 485, in __init__
          self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
        File "C:\Python\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
          raise distutils.errors.DistutilsPlatformError(err)
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\bizma\AppData\Local\Temp\pip-install-3gk75wka\cffi\
  ----------------------------------------
ERROR: Command "'C:\Python\python.exe' 'C:\Python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\bizma\AppData\Local\Temp\pip-build-env-ixx_vfsk\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cffi>=1.4.1; python_implementation != '"'"'PyPy'"'"''" failed with error code 1 in None
```

**Comment by jerbob** [comment]
Hi @laynd, it looks like `cffi` requires you to install the C++ build tools from https://visualstudio.microsoft.com/visual-cpp-build-tools/. Make sure you have the following checked when running the installer:

![image](https://user-images.githubusercontent.com/25161069/57490652-d633af00-72b1-11e9-8c27-5fb5a69c691c.png)

**Comment by laynd** [comment]
Thank you for response! Now I hit the next roadblock... What could be causing this issue? 

```
Building wheels for collected packages: PyNaCl
  Building wheel for PyNaCl (PEP 517) ... error
  ERROR: Complete output from command 'C:\Python\python.exe' 'C:\Python\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\bizma\AppData\Local\Temp\tmp5dg3wsls':
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\nacl
  copying src\nacl\encoding.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\exceptions.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\hash.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\hashlib.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\public.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\secret.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\signing.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\utils.py -> build\lib.win-amd64-3.8\nacl
  copying src\nacl\__init__.py -> build\lib.win-amd64-3.8\nacl
  creating build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\argon2i.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\argon2id.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\scrypt.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\_argon2.py -> build\lib.win-amd64-3.8\nacl\pwhash
  copying src\nacl\pwhash\__init__.py -> build\lib.win-amd64-3.8\nacl\pwhash
  creating build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_aead.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_box.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_generichash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_hash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_kx.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_pwhash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_secretstream.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_shorthash.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\crypto_sign.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\randombytes.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\sodium_core.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\utils.py -> build\lib.win-amd64-3.8\nacl\bindings
  copying src\nacl\bindings\__init__.py -> build\lib.win-amd64-3.8\nacl\bindings
  running build_clib
  Traceback (most recent call last):
    File "C:\Python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "C:\Python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 140, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\bizma\AppData\Local\Temp\pip-build-env-1fzucafg\overlay\Lib\site-packages\setuptools\build_meta.py", line 192, in build_wheel
      self.run_setup()
    File "C:\Users\bizma\AppData\Local\Temp\pip-build-env-1fzucafg\overlay\Lib\site-packages\setuptools\build_meta.py", line 233, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\bizma\AppData\Local\Temp\pip-build-env-1fzucafg\overlay\Lib\site-packages\setuptools\build_meta.py", line 141, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 208, in <module>
      setup(
    File "C:\Users\bizma\AppData\Local\Temp\pip-build-env-1fzucafg\overlay\Lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Python\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\bizma\AppData\Local\Temp\pip-build-env-1fzucafg\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Python\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 159, in run
      raise Exception("ERROR: The 'make' utility is missing from PATH")
  Exception: ERROR: The 'make' utility is missing from PATH
  ----------------------------------------
  ERROR: Failed building wheel for PyNaCl
  Running setup.py clean for PyNaCl
Failed to build PyNaCl
ERROR: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
```

**Comment by jerbob** [comment]
Hi @laynd, 

You may have to install [Cygwin](http://www.cygwin.com/install.html) to have access to the `make` command.

Sorry, I haven't really tested installations on Windows yet. I'll work on making the process simpler.

**Comment by laynd** [comment]
After having no success with 'make' command (even after installing Cygwin) decided to reinstall python. I had beta version and some ppl indicated that it could be the reason why I am having issues with 'make' command. After installation of the current stable release of python now I am having issues with 'git clone' command. So far unable to figure out why it cannot clone obviously existing repository... 

```
C:\Users\bizma\Documents\GitHub\groupme-discord>py -m pip install -r requirements.txt
Collecting Flask>=1.0.2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting aiohttp>=3.3.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/bd/08f0900d62b4ea1ca10bb2e2a1596ac3b04024c7daf7350debee0bd022fb/aiohttp-3.5.4-cp37-cp37m-win_amd64.whl
Collecting requests>=2.18.4 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py/archive/rewrite.zip#egg=discord.py[voice] (from -r requirements.txt (line 4))
  Cloning https://github.com/Rapptz/discord.py/archive/rewrite.zip to c:\users\bizma\appdata\local\temp\pip-install-466z185y\discord.py
  Running command git clone -q https://github.com/Rapptz/discord.py/archive/rewrite.zip 'C:\Users\bizma\AppData\Local\Temp\pip-install-466z185y\discord.py'
  remote: Not Found
  fatal: repository 'https://github.com/Rapptz/discord.py/archive/rewrite.zip/' not found
ERROR: Command "git clone -q https://github.com/Rapptz/discord.py/archive/rewrite.zip 'C:\Users\bizma\AppData\Local\Temp\pip-install-466z185y\discord.py'" failed with error code 128 in None 
```

**Comment by jerbob** [comment]
@laynd discord.py recently released their rewrite branch to PyPi, which is why my requirements.txt was outdated. I've updated the repo accordingly, so try cloning it and try again.

**Comment by laynd** [comment]
Thank you for updating requirements.txt! Finally installation itself worked without a hitch. However, when running main.py it throws an error. 

```

C:\Users\bizma\Documents\GitHub\groupme-discord>py main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    discord_bot.main()
  File "C:\Users\bizma\Documents\GitHub\groupme-discord\discord_bot.py", line 99, in main
    Process(target=bot.run, args=(BOT_TOKEN,)).start()
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'WeakSet.__init__.<locals>._remove'


C:\Users\bizma\Documents\GitHub\groupme-discord>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied


```

**Comment by laynd** [comment]
On forums found that previous error was a bug in Python 3.7.2. Upgraded to 3.7.3 and getting a different error. This one seems to be code related. On forums found some indication that it could be related to multiprocessing method used spawn for windows and fork for linux...
```

C:\Users\bizma\Documents\GitHub\groupme-discord>py main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    discord_bot.main()
  File "C:\Users\bizma\Documents\GitHub\groupme-discord\discord_bot.py", line 99, in main
    Process(target=bot.run, args=(BOT_TOKEN,)).start()
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'WeakSet.__init__.<locals>._remove'

C:\Users\bizma\Documents\GitHub\groupme-discord>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\bizma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```

**Comment by laynd** [comment]
Should I just give up on windows solution? Is it going to be a better idea if I will put Linux on old MacBook I have and use it to run this discord/groupme bridge?
