### ISSUE TITLE
Linux Discord Bot Token Issue

### ISSUE THREAD

**Issue by laynd** [AnonGuy/groupme-discord#16]
Trying to run it on linux. Everything else installed without a hitch, however, got an issue with Discord token. Token copy pasted into config.ini 

```
 * Serving Flask app "web_server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Task exception was never retrieved
future: <Task finished coro=<Client.run.<locals>.runner() done, defined at /home/daniel/.local/lib/python3.6/site-packages/discord/client.py:545> exception=LoginFailure('Improper token has been passed.',)>
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.6/site-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/daniel/.local/lib/python3.6/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.6/site-packages/discord/client.py", line 547, in runner
    await self.start(*args, **kwargs)
  File "/home/daniel/.local/lib/python3.6/site-packages/discord/client.py", line 510, in start
    await self.login(*args, bot=bot)
  File "/home/daniel/.local/lib/python3.6/site-packages/discord/client.py", line 376, in login
    await self.http.static_login(token, bot=bot)
  File "/home/daniel/.local/lib/python3.6/site-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

**Comment by jerbob** [comment]
Try changing the line in `config.ini` from
```ini
bot_token = 'TOKEN'
```
to:
```ini
bot_token=TOKEN
```
if that doesn't work, run the following before starting:
```bash
export DISCORD_BOT_TOKEN=TOKEN
```

**Comment by laynd** [comment]
`bot_token=TOKEN` 
change solved the problem and service started. 
Now need to figure out why NGROK giving me internal server error 500...

**Comment by laynd** [comment]
```
[2019-05-18 11:12:31,710] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daniel/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daniel/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daniel/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/daniel/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daniel/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daniel/Desktop/groupme-discord/web_server.py", line 23, in index
    'avatar_url': message_object['avatar_url']
  File "/home/daniel/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/daniel/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/daniel/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/daniel/.local/lib/python3.6/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/daniel/.local/lib/python3.6/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for ''https://discordapp.com/api/webhooks/579125916228386826/rpz0GGrMM0IUlYLDVgyqgZvvLaAcGlmj-qp0xrT2nBIsQgBFLbUCQ3vmVrfFXGg1fEJI''
127.0.0.1 - - [18/May/2019 11:12:31] "POST / HTTP/1.1" 500 -
```

**Comment by laynd** [comment]
Found a solution, needed to remove all " ' " symbols and do the same as with bot token. Now bridge is operational

**Comment by jerbob** [comment]
Oh that's great! I'll update the guide
